name: Create Docker Release

on:
  push:
    tags:
      - "*"

jobs:
  call-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_tag: ${{ github.ref_name }}
      also_tag_latest: true
