name: Docker Image Builder

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      also_tag_latest:
        required: false
        type: boolean
        default: false

jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            alexandrevsd/kepler:${{ inputs.image_tag }}
            ${{ inputs.also_tag_latest && 'alexandrevsd/kepler:latest' || '' }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexandrevsd/kepler
          short-description: "Kepler Server – multi-platform Docker image"
          readme-filepath: ./README.md
